color0 #14303e
color1 #fd4663
color2 #67bae4
color3 #5c6fd6
color4 #8864ce
color5 #93ceec
color6 #96a3e9
color7 #f2f2f3
color8 #606e74
color9 #fd4663
color10 #67bae4
color11 #5c6fd6
color12 #8864ce
color13 #93ceec
color14 #96a3e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #0f242f
background            #0f242f
foreground            #f2f2f3
selection_foreground  #afb4b6
selection_background  #14303e
active_border_color   #67bae4
inactive_border_color #14303e
url_color             #67bae4

active_tab_foreground   #182125
active_tab_background   #67bae4
inactive_tab_foreground #afb4b6
inactive_tab_background #14303e
cursor_trail_color      #afb4b6
