pragma Singleton

import Quickshell
import Quickshell.Io

/**
 * Singleton to read colors generated by pywal.
 */
Singleton {
    id: root

    readonly property var walColorsPath: Quickshell.env("HOME") + "/.cache/wal/colors.json"
    readonly property var data: JSON.parse(walColorsFile.text())

    // colors provided by pywal

    property string bg: data.special.background
    property string fg: data.special.foreground
    property string c0: data.colors.color0
    property string c1: data.colors.color1
    property string c2: data.colors.color2
    property string c3: data.colors.color3
    property string c4: data.colors.color4
    property string c5: data.colors.color5
    property string c6: data.colors.color6
    property string c7: data.colors.color7
    property string c8: data.colors.color8
    property string c9: data.colors.color9
    property string c10: data.colors.color10
    property string c11: data.colors.color11
    property string c12: data.colors.color12
    property string c13: data.colors.color13
    property string c14: data.colors.color14
    property string c15: data.colors.color15

    FileView {
        id: walColorsFile
        path: root.walColorsPath
        watchChanges: true
        onFileChanged: reload()
    }
}
