pragma Singleton

import Quickshell
import Quickshell.Io

/**
 * Singleton to read colors generated by pywal.
 */
Singleton {
    id: root

    readonly property var walColorsPath: Quickshell.env("HOME") + "/.cache/wal/colors.json"
    readonly property var data: JSON.parse(walColorsFile.text())

    // colors provided by pywal

    property JsonObject colors: JsonObject {
        property string bg: root.data.special.background
        property string fg: root.data.special.foreground
        property string c0: root.data.colors.color0
        property string c1: root.data.colors.color1
        property string c2: root.data.colors.color2
        property string c3: root.data.colors.color3
        property string c4: root.data.colors.color4
        property string c5: root.data.colors.color5
        property string c6: root.data.colors.color6
        property string c7: root.data.colors.color7
        property string c8: root.data.colors.color8
        property string c9: root.data.colors.color9
        property string c10: root.data.colors.color10
        property string c11: root.data.colors.color11
        property string c12: root.data.colors.color12
        property string c13: root.data.colors.color13
        property string c14: root.data.colors.color14
        property string c15: root.data.colors.color15
    }

    property string background: Config.options.dark ? this.colors.bg : this.colors.fg
    property string foreground: Config.options.dark ? this.colors.fg : this.colors.bg

    FileView {
        id: walColorsFile
        path: root.walColorsPath
        blockLoading: true
        watchChanges: true
        onFileChanged: reload()
    }
}
