# Shell variables
# Generated by 'wal'
wallpaper="/home/octopod/.cache/quickshell/user/generated/wallpaper"

# Special
background='#06061a'
foreground='#c1c1c5'
cursor='#c1c1c5'

# Colors
color0='#06061a'
color1='#c4705d'
color2='#b25a73'
color3='#5fab62'
color4='#51a0b4'
color5='#b29d60'
color6='#b78067'
color7='#8d8d98'
color8='#454580'
color9='#f6a18d'
color10='#dc8ba2'
color11='#90d494'
color12='#7ecce0'
color13='#ddc992'
color14='#e3b29c'
color15='#c1c1c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
