--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/octopod/.cache/quickshell/user/generated/wallpaper"

-- Special
background="#06061a"
foreground="#c1c1c5"
cursor="#c1c1c5"

-- Colors
color0="#06061a"
color1="#c4705d"
color2="#b25a73"
color3="#5fab62"
color4="#51a0b4"
color5="#b29d60"
color6="#b78067"
color7="#8d8d98"
color8="#454580"
color9="#f6a18d"
color10="#dc8ba2"
color11="#90d494"
color12="#7ecce0"
color13="#ddc992"
color14="#e3b29c"
color15="#c1c1c5"
