[colors]
background = '#0a0a178e'
black = '#0a0a17'
blue = '#eaa99a'
cursor = '#c1c1c5'
cyan = '#8ec3d0'
foreground = '#c1c1c5'
green = '#d7b7a9'
magenta = '#a0c5a2'
red = '#cfc3a1'
tabs = '#c1c1c5'
tabs-active = '#ce9aa9'
white = '#c1c1c5'
yellow = '#c1c1c5'
dim-black = '#0a0a178e'
dim-blue = '#eaa99a8e'
dim-cyan = '#8ec3d08e'
dim-foreground = '#c1c1c58e'
dim-green = '#d7b7a98e'
dim-magenta = '#a0c5a28e'
dim-red = '#cfc3a18e'
dim-white = '#ce9aa98e'
dim-yellow = '#c1c1c58e'
light-black = '#eaa99a'
light-blue = '#8ec3d0'
light-cyan = '#d7b7a9'
light-foreground = '#a0c5a2'
light-green = '#cfc3a1'
light-magenta = '#ce9aa9'
light-red = '#c1c1c5'
light-white = '#eaa99a'
light-yellow = '#8ec3d0'
