foreground         #c1c1c5
background         #0a0a17
background_opacity 1.0
cursor             #c1c1c5

active_tab_foreground     #0a0a17
active_tab_background     #c1c1c5
inactive_tab_foreground   #c1c1c5
inactive_tab_background   #0a0a17

active_border_color   #c1c1c5
inactive_border_color #0a0a17
bell_border_color     #eaa99a

color0       #0a0a17
color8       #59596d
color1       #eaa99a
color9       #eaa99a
color2       #8ec3d0
color10      #8ec3d0
color3       #d7b7a9
color11      #d7b7a9
color4       #a0c5a2
color12      #a0c5a2
color5       #cfc3a1
color13      #cfc3a1
color6       #ce9aa9
color14      #ce9aa9
color7       #c1c1c5
color15      #c1c1c5
