[colors.primary]
background = "#0a0a17"
foreground = "#c1c1c5"

[colors.cursor]
text = "#0a0a17"
cursor = "#c1c1c5"

[colors.vi_mode_cursor]
text = "#0a0a17"
cursor = "#c1c1c5"

[colors.search.matches]
foreground = "#0a0a17"
background = "#c1c1c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#59596d"
background = "#c1c1c5"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0a0a17"
red = "#eaa99a"
green = "#8ec3d0"
yellow = "#d7b7a9"
blue = "#a0c5a2"
magenta = "#cfc3a1"
cyan = "#ce9aa9"
white = "#c1c1c5"

[colors.bright]
black = "#59596d"
red = "#eaa99a"
green = "#8ec3d0"
yellow = "#d7b7a9"
blue = "#a0c5a2"
magenta = "#cfc3a1"
cyan = "#ce9aa9"
white = "#c1c1c5"

[colors.dim]
black = "#c1c1c5"
red = "#eaa99a"
green = "#cfc3a1"
yellow = "#d7b7a9"
blue = "#a0c5a2"
magenta = "#8ec3d0"
cyan = "#ce9aa9"
white = "#59596d"

