# pywal theme for ghostty

background = 0a0a17
foreground = c1c1c5
cursor-color = c1c1c5
selection-background = c1c1c5
selection-foreground = 0a0a17

palette = 0=#0a0a17
palette = 1=#eaa99a
palette = 2=#8ec3d0
palette = 3=#d7b7a9
palette = 4=#a0c5a2
palette = 5=#cfc3a1
palette = 6=#ce9aa9
palette = 7=#c1c1c5
palette = 8=#59596d
palette = 9=#eaa99a
palette = 10=#8ec3d0
palette = 11=#d7b7a9
palette = 12=#a0c5a2
palette = 13=#cfc3a1
palette = 14=#ce9aa9
palette = 15=#c1c1c5
